stages:
  - build
  - deploy

.gradle-image: &gradle-image
  image: gradle:5.5-jdk12

.dind-service: &dind-service
  services:
    - docker:17.09.0-ce-dind

build:
  <<: *gradle-image
  <<: *dind-service
  stage: build
  variables:
    DOCKER_IO_PASSWORD: $DOCKER_IO_PASSWORD
    # Instruct TestContainers to use the daemon of DinD
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - gradle test build jib

deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud components install kubectl --quiet
    - echo "$GOOGLE_CREDENTIALS" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud container clusters get-credentials ${BEER_CLUSTER} --zone ${BEER_ZONE} --project ${BEER_K8S_PROJECT}
  script:
    - kubectl set image deployment/beer-api beer-api=hives/beer-api:latest
    - kubectl get pods
